version: '3.1'
services:
  api:
    container_name: api
    build: .
    image: backend
    restart: always
    command: "/bin/sh -c 'npx prisma migrate dev; npx prisma db seed; npm start'"
    volumes:
      - ./dist/:/usr/src/backend/dist/
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/data/db
    ports:
      - 5432:5432
